BOARD=panther-x2-vendor
BRANCH=vendor
RELEASE=trixie

BUILD_MINIMAL=no
BUILD_DESKTOP=no

KERNEL_CONFIGURE=no
KERNEL_BTF=no

PACKAGE_LIST_ADDITIONAL="device-tree-compiler v4l-utils i2c-tools ethtool pciutils usbutils"
